name: kuberform

on:
  push:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Get PR Labels
        id: getLabelNames
        uses: grant350/get_latest_merged_pull_request_labels@v1.1
        with:
          token: ${{github.token}}
      - name: set version type
        if:  contains(steps.getLabelNames.outputs.labelNames,'patch')
        run: echo "is patch"
      - if:  contains(steps.getLabelNames.outputs.labelNames,'minor')
        run: echo "is minor"
      - if:  contains(steps.getLabelNames.outputs.labelNames,'major')
        run: echo "is major"

  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    #  uses custom action
    # - name: add patch
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: |
    #       npm version ${{ env.VersionType}}; \
    #       git config user.name 'grant350'; \
    #       git config user.email github-actions@github.com; \
    #       git add .; \
    #       git commit -m "version controll ${{ env.VersionType}}"; \
    #       git push


    #   if pr is merged get the label from the merged pr and find a way to update the main branch

    # - name: install app-src modules
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm install

    # - name: install root modules
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm install

    # - name: build
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run build

    # - name: rollup kuberform
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm run rollup
    #   # npm version patch, minor, major

    # - name: update node
    # - name: commit and push to main with updated npm version