name: kuberform

on:
  push:
    branches:
      - main
jobs:

  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get PR Labels
      id: getLabelNames
      uses: grant350/getPullRequestLabels@v1.1
      with:
        token: ${{github.token}}
    - name: set version type
      if:  contains(steps.getLabelNames.outputs.labelNames,'patch')
      run: echo "VersionType=patch" >> $GITHUB_ENV
    - if:  contains(steps.getLabelNames.outputs.labelNames,'minor')
      run: echo "VersionType=minor" >> $GITHUB_ENV
    - if:  contains(steps.getLabelNames.outputs.labelNames,'major')
      run: echo "VersionType=major" >> $GITHUB_ENV
    - name: install app-src modules
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: npm install

    - name: install root modules
      working-directory: /home/runner/work/kuberform/kuberform
      run: npm install

    - name: build
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: npm run build

    - name: rollup kuberform
      working-directory: /home/runner/work/kuberform/kuberform
      run: npm run rollup

    - name: add version to repo
      working-directory: /home/runner/work/kuberform/kuberform
      run: |
          git config user.name 'grant350'; \
          git config user.email 'soundbreakr1@gmail.com'; \
          npm version "${{env.VersionType}}"; \
          git add .; \
          git commit -m "version control ${{env.VersionType}}"; \
          git push