name: kuberform

on:
  push:
    branches:
      - main
jobs:

  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{github.token}}

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{secrets.NPMJS_TOKEN}}
        working-directory: /home/runner/work/kuberform/kuberform/app-src
        run: |
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN} \
            npm publish


