name: kuberform

on:
  push:
    branches:
      - main
jobs:

  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{github.token}}
        env:
          NPM_TOKEN: ${{secrets.GITHUBACTIONNPM}}
      - name: Publish to NPM
        run: |
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
            npm publish

      - name: deploy to npmjs
        run: echo 'deploy api'
