name: kuberform

on:
  push:
    branches:
      - main
jobs:

  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{github.token}}

      - name: Publish to NPM
        run: |
            npm set https://registry.npmjs.org/@kuberspace%2fkuberform/:_authToken=$GITHUBACTIONNPM
            npm publish

      - name: deploy to npmjs
        run: echo 'deploy api'
