name: kuberform
on:
  push:
    branches:
      - main
jobs:

  buildKuberform:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{secrets.NPMJS_TOKEN}}
        run: |
            cat package.json \
            npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN} \
            npm publish


