name: kuberform
on:
  pull_request:
    types: [opened]
jobs:
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
# check main version to see if its off and update branch if version is off
    - name: Get PR Labels
      id: getLabelNames
      uses: grant350/getPullRequestLabels@v1.1
      with:
        token: ${{github.token}}
    - if:  contains(steps.getLabelNames.outputs.labelNames,'patch')
      run: echo "VersionType=patch" >> $GITHUB_ENV
    - if:  contains(steps.getLabelNames.outputs.labelNames,'minor')
      run: echo "VersionType=minor" >> $GITHUB_ENV
    - if:  contains(steps.getLabelNames.outputs.labelNames,'major')
      run: echo "VersionType=major" >> $GITHUB_ENV;

    - name: Throw error if VersionType is empty
      if: "${{ env.VersionType == '' }}"
      run: echo "Error no versionType!"; exit 125

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{github.token}}

    - name: install app-src modules
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: npm install

    - name: install root modules
      working-directory: /home/runner/work/kuberform/kuberform
      run: npm install

    - name: build
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: npm run build

    - name: test the code
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: npm test

    - name: check Linting
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: npm run linter

    - name: build
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: npm run build

    - name: rollup kuberform
      working-directory: /home/runner/work/kuberform/kuberform
      run: npm run rollup

    - name: add version to repo
      working-directory: /home/runner/work/kuberform/kuberform/app-src
      run: |
          git config user.name 'grant350'; \
          git config user.email 'soundbreakr1@gmail.com'; \
          npm version --no-git-tag-version "${{env.VersionType}}"; \
          cd .. ;
          npm version --no-git-tag-version "${{env.VersionType}}"; \
          git add . ; \
          git commit -m "version control commit ${{env.VersionType}}"; \
          git push --force;
