name: kuberform

on: [pull_request]

jobs:
  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:
    - name: git a label
      working-directory: /home/runner/work/kuberform/kuberform
      run: echo | github.event.pull_request.labels

    - name: grab git tag and store it in env
      working-directory: /home/runner/work/kuberform/kuberform
      run: echo | git describe --tags

    - name: git checkout
      uses: actions/checkout@v3


    # - name: install app-src modules
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm install

    # - name: install root modules
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm install

    # - name: test the code
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm test

    # - name: check Linting
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run linter

    # - name: build
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run build

    # - name: rollup kuberform
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm run rollup
    #   # npm version patch, minor, major