name: kuberform

on: [pull_request]

jobs:
  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']

    steps:

    - name: See if patch label exists
      if: contains(github.event.pull_request.labels.*.name,'patch')
      run: echo "VersionType=patch" >> $GITHUB_ENV

    - name: See if minor label exists
      if: contains(github.event.pull_request.labels.*.name,'minor')
      run: echo "VersionType=minor" >> $GITHUB_ENV

    - name: See if major label exists
      if: contains(github.event.pull_request.labels.*.name,'major')
      run: echo "VersionType=major" >> $GITHUB_ENV

    - name: Throw error if VersionType is empty
      if: "${{ env.VersionType == '' }}"
      run: echo "Error!"; exit 125

    - name: Install nvm
      run: |
          git clone git://github.com/creationix/nvm.git ~/.nvm
      # /home/runner/.nvm

    - name: Checkout
      uses: actions/checkout@v3
    - run: |
          nvm ${{ env.VersionType}} \
          git config user.name GitHub Actions Bot \
          git config user.email github-actions@github.com \
          git add . \
          git commit -m "version controll ${{ env.VersionType}}" \
          git push


    #   if pr is merged get the label from the merged pr and find a way to update the main branch

    # - name: install app-src modules
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm install

    # - name: install root modules
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm install

    # - name: test the code
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm test

    # - name: check Linting
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run linter

    # - name: build
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run build

    # - name: rollup kuberform
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm run rollup
    #   # npm version patch, minor, major