name: kuberform

on: [pull_request]

jobs:
  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:

    - name: Dump GitHub context
      id: github_context_step
      run: echo '${{ toJSON(github.event.pull_request.labels) }}'

    - name: see if patch label exists
      if: contains(${{github.event.pull_request.labels.*.name}},'patch')
      run: echo 'patch label exists'

    - name: see if minor label exists
      if: contains(github.event.pull_request.labels.*.name,'minor')
      run: echo 'minor label exists'

    - name: see if major label exists
      if: contains(github.event.pull_request.labels.*.name,'major')
      run: echo 'major label exists'

    - name: git checkout
      uses: actions/checkout@v3

    #   if pr is merged get the label from the merged pr and find a way to update the main branch

    # - name: install app-src modules
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm install

    # - name: install root modules
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm install

    # - name: test the code
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm test

    # - name: check Linting
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run linter

    # - name: build
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run build

    # - name: rollup kuberform
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm run rollup
    #   # npm version patch, minor, major