name: kuberform

on: [pull_request]

jobs:
  buildKuberform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.0']
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: grab git tag and store it in env
      run: echo git describe --tags --abbrev=0

    - name: check GITHUB_REF
      run: echo $env:GITHUB_REF

    # - name: install app-src modules
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm install

    # - name: install root modules
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm install

    # - name: test the code
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm test

    # - name: check Linting
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run linter

    # - name: build
    #   working-directory: /home/runner/work/kuberform/kuberform/app-src
    #   run: npm run build

    # - name: rollup kuberform
    #   working-directory: /home/runner/work/kuberform/kuberform
    #   run: npm run rollup
    #   # npm version patch, minor, major